---
name: smart_save
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: null
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  firebase_analytics: ^10.8.7
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: null
  build_runner: ^2.4.8
  freezed: ^2.4.7


flutter_launcher_icons:
  android: launcher_icons
  ios: true
  image_path: assets/logo.png
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/vetted_images/
  - assets/strict_images/
  - assets/flexible_images/
  - assets/money_talks_images/
